<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NewRich.Domain\NewRich.Domain.csproj" />
    <ProjectReference Include="..\NewRich.Shared\NewRich.Shared.csproj" />
    <ProjectReference Include="..\NewRich.Constants\NewRich.Constants.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
