<Project>
  <PropertyGroup>
    <AndroidKeyStore>true</AndroidKeyStore>
    <AndroidSigningKeyStore>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\..\signing\produccion.keystore'))</AndroidSigningKeyStore>
    <AndroidSigningKeyAlias>androiddebugkey</AndroidSigningKeyAlias>
    <AndroidSigningStorePass>android</AndroidSigningStorePass>
    <AndroidSigningKeyPass>android</AndroidSigningKeyPass>
  </PropertyGroup>
</Project>
